#!/bin/bash

# Build docker image
git clone https://github.com/makuk66/docker-solr.git /tmp/dokku-solr-dockerfiles
docker build -q=true -t makuk66/docker-solr /tmp/dokku-solr-dockerfiles
rm -rf /tmp/dokku-solr-dockerfiles
