#!/bin/bash
set -e;

APP="$1"

PLUGIN_NAME=solr
MAINTAINER=makuk66
CONTAINER_DATA_DIR=/data/solr/shared
DOCKER_IMAGE="$MAINTAINER/$PLUGIN_NAME"
SOLR_APP_IMAGE="$PLUGIN_NAME/$APP"

if [[ -z "$APP" ]]; then
    echo "Error: You must specify an app" >&2
    exit
fi

# Check if an existing DB volume exists
SOLR_APP_IMAGE_ID=$(docker images | grep "$SOLR_APP_IMAGE" | awk '{ print $3 }')
if [[ -n $SOLR_APP_IMAGE_ID ]]; then
    echo    "-----> Checking status of Solr"

    # Check if Solr container is installed
    SOLR_IMAGE=$(docker images | grep "$DOCKER_IMAGE" | awk '{ print $3 }')
    if [[ -z $SOLR_IMAGE ]]; then
        echo "Solr image not found... Did you run 'dokku plugins-install' ?"
        exit 1
    fi

    echo    "       Found image solr/$APP database"
    echo -n "       Checking status... "

    SOLR_APP_CONTAINER_ID=$(docker ps | grep "$SOLR_APP_IMAGE" | awk '{ print $1 }')
    if [[ -n $SOLR_APP_CONTAINER_ID ]]; then
        echo "ok."
    else
        echo "stopped."

        SOLR_DATA_VOLUME="$DOKKU_ROOT/$APP/$PLUGIN_NAME/volumes/data:$CONTAINER_DATA_DIR"

        echo -n "       Launching $SOLR_APP_IMAGE... "
        echo "COMMAND: docker run -v $SOLR_DATA_VOLUME -d $SOLR_APP_IMAGE /bin/bash -c \"cd /opt/solr/example; java -jar start.jar\""
        ID=$(docker run -v $SOLR_DATA_VOLUME -d --name solr $SOLR_APP_IMAGE /bin/bash -c "cd /opt/solr/example; java -jar start.jar")
        sleep 1
        echo "ok."
    fi
fi
